language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
    - BuildTools
before_install:
  - 'date'
  - 'mkdir -p BuildTools'
  - 'cd BuildTools'
  - 'curl -z BuildTools.jar -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar'
  - 'java -jar BuildTools.jar --rev 1.12.2 --compile-if-changed'
  - 'cd ..'
script:
  - 'mvn deploy --batch-mode -V -s settings.xml
'
